FROM node:11.13.0-alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

# If you are building your code for production
# RUN npm ci --only=production

COPY . .

EXPOSE 4000
CMD [ "node", "app.js" ]