FROM node:11.13.0-alpine

ENV NPM_CONFIG_LOGLEVEL warn
ARG app_env
ENV APP_ENV $app_env

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY . .

CMD if [ ${APP_ENV} = production ]; \
	then \
	npm install -g http-server && \
	npm run build && \
	node index.js; \
	else \
	npm run start; \
	fi

EXPOSE 3000